In [1]:
import numoy as np

ModuleNotFoundError: No module named 'numoy'

In [2]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
from time import process_time


In [6]:
python_list = [i for i in range(10000)]
start_time= process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0010874300000001114


In [7]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time=process_time()
print(end_time - start_time)

0.00019982100000071057


In [8]:
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [10]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

# not sepearted by commas

[1 2 3 4 5]


numpy.ndarray

In [11]:
#creating a one dimensional array

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [13]:
a.shape

(5,)

In [15]:
b = np.array([(1,2,3,4,5),(5,6,7,8,9)])
print(b)
b.shape


[[1 2 3 4 5]
 [5 6 7 8 9]]


(2, 5)

In [16]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in numpy array


In [18]:
#create a numpy array of zeroes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
#create a numpy array as ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
#create an array of particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [21]:
#create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
#create an numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.17075994 0.28557571 0.45505453 0.04086255]
 [0.09297304 0.74414403 0.51192304 0.80083258]
 [0.34012301 0.94112627 0.66997266 0.50806267]]


In [25]:
#random values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)


[[85 73 99 25 59]
 [20 55 21 93 14]
 [12 70 26 93 98]]


In [26]:
#create an array with evenely spaced values
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [27]:
#array of evenly spaced values we have to specify the steps
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [29]:
#convert a list to an array
list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)

[10 20 30 40 50]


Analysing a particular array

In [30]:
c = np.random.randint(10,90,(5,5))
print(c)

[[20 62 50 64 10]
 [24 23 46 68 19]
 [63 43 56 77 54]
 [35 38 53 39 80]
 [31 75 16 17 70]]


In [31]:
print(c.shape)
#array dimension

(5, 5)


In [32]:
#number of dimensions
print(c.ndim)

2


In [33]:
#number of elements in the array
print(c.size)

25


In [34]:
#checking data type of values in the array
print(c.dtype)

int64


Mathematical operations that can be performed on the array

In [35]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [36]:
a = np.random.randint(0,10,(3,3))
b= np.random.randint(10,20,(3,3))
print(a)
print(b)

[[3 0 2]
 [3 2 9]
 [4 8 9]]
[[12 15 16]
 [10 15 16]
 [11 12 15]]


In [37]:
print(a+b)

[[15 15 18]
 [13 17 25]
 [15 20 24]]


In [39]:
print(a-b)
print(a*b)
print(a/b)

[[ -9 -15 -14]
 [ -7 -13  -7]
 [ -7  -4  -6]]
[[ 36   0  32]
 [ 30  30 144]
 [ 44  96 135]]
[[0.25       0.         0.125     ]
 [0.3        0.13333333 0.5625    ]
 [0.36363636 0.66666667 0.6       ]]


In [42]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 15 18]
 [13 17 25]
 [15 20 24]]
[[ -9 -15 -14]
 [ -7 -13  -7]
 [ -7  -4  -6]]
[[ 36   0  32]
 [ 30  30 144]
 [ 44  96 135]]
[[0.25       0.         0.125     ]
 [0.3        0.13333333 0.5625    ]
 [0.36363636 0.66666667 0.6       ]]


Array manipulation

In [43]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 5 6]
 [0 9 1]]
(2, 3)


In [44]:
trans = np.transpose(array)
print(trans)

[[5 0]
 [5 9]
 [6 1]]


In [45]:
array = np.random.randint(0,10,(2,3))
print(array)
trans2 = array.T
print(trans2)

[[9 7 2]
 [0 0 0]]
[[9 0]
 [7 0]
 [2 0]]


In [47]:
#reshaping the array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[1 7 6]
 [9 3 3]]
(2, 3)


In [50]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[1 7]
 [6 9]
 [3 3]]
(3, 2)
